name: michaelp-anthwlock-untrunc
version: "0.1-testing"
summary: Restore a damaged (truncated) mp4, m4v, mov, 3gp video
description: |
  Restore a damaged (truncated) mp4, m4v, mov, 3gp video. Provided you have a similar not broken video. And some luck.
license: GPL-2.0
base: core18

grade: stable
confinement: strict

apps:
  untrunc: 
    command: app/untrunc
    plugs: [home, removable-media]

parts:
  anthwlock-untrunc:
    source: .
    plugin: make
    override-build: |
      echo "Running override-build script"
      make FF_VER=3.3.9
      strip untrunc
      mkdir -p $SNAPCRAFT_PART_INSTALL/app
      rm -rf $SNAPCRAFT_PART_INSTALL/app/*
      mv untrunc $SNAPCRAFT_PART_INSTALL/app
    build-packages:
      - yasm
      - wget
      - g++
      - make
      - git
      - ca-certificates
      - xz-utils
      - libc6
      - libavutil-dev
      - libavformat-dev
      - build-essential
   
    stage-packages:
      - libx11-6
      - libva-drm2
      - libva2
      - libva-x11-2

      
